spring.application.name=wayon-backend

server.port=8080

spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:dcbapp
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=${user:wayon}
spring.datasource.password=${password:wayon}

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

server.servlet.context-path=/dev/api/v1/wayon

#springdoc.swagger-ui.path=/swagger-ui
#springdoc.swagger-ui.show-common-extensions=true