spring.application.name=wayon-backend

spring.profiles.active=${ENV_PROFILE:dev}
server.port=${SERVER_PORT}

spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:dcbapp
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=${user}
spring.datasource.password=${password}

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

server.servlet.context-path=/api/v1/wayon

springdoc.swagger-ui.path=/swagger-ui
springdoc.swagger-ui.show-common-extensions=true